# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_station_app', '0006_auto_20161231_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='record',
            name='field2',
        ),
        migrations.AlterField(
            model_name='channel',
            name='last_update',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='field',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_station_app.Record'),
        ),
    ]
