# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_station_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='reg_time',
            new_name='insertion_time',
        ),
    ]
