# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sest', '0013_auto_20170203_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='sest.Record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='insertion_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='registration date and time'),
        ),
    ]
