# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sest', '0014_auto_20170206_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sest.Record'),
        ),
    ]
