# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sest', '0005_auto_20161228_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='write_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
