# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sest', '0010_auto_20170131_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionAndReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=20)),
                ('field_no', models.PositiveSmallIntegerField()),
                ('value_optional', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(max_length=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sest.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sest.User')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='notification_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sest.NotificationEmail'),
        ),
    ]
