# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sest', '0011_auto_20170202_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditionandreaction',
            old_name='value',
            new_name='_value',
        ),
        migrations.RenameField(
            model_name='conditionandreaction',
            old_name='value_optional',
            new_name='_value_optional',
        ),
    ]
