# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sest', '0016_auto_20170207_2109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldencoding',
            unique_together=set([('channel', 'field_no')]),
        ),
    ]
