# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sest', '0017_auto_20170209_1238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=set([('record', 'field_no')]),
        ),
    ]
