# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sest', '0018_auto_20170209_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_no', models.PositiveSmallIntegerField()),
                ('encoding', models.CharField(max_length=50)),
                ('name', models.CharField(default='-', max_length=100)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sest.Channel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fieldencoding',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='fieldencoding',
            name='channel',
        ),
        migrations.DeleteModel(
            name='FieldEncoding',
        ),
        migrations.AlterUniqueTogether(
            name='fieldmetadata',
            unique_together=set([('channel', 'field_no')]),
        ),
    ]
